import { ChatOpenAI } from "@langchain/openai";
import { SYSTEM_HEADER } from "../constitution.js";
import type { AgentStateType } from "../state.js";

const llm = process.env.OPENAI_API_KEY
  ? new ChatOpenAI({ model: "gpt-4o-mini", apiKey: process.env.OPENAI_API_KEY })
  : null;

export async function writeCodeNode(state: AgentStateType): Promise<Partial<AgentStateType>> {
  let newCode = `// Auto-generated by Microfyxd\n// Target: ${state.targetFile || "unknown"}\nexport default function handler(req, res) {\n  res.json({ status: "ok", source: "microfyxd" });\n}`;

  if (llm) {
    try {
      const res = await llm.invoke([
        { role: "system", content: SYSTEM_HEADER + "\nYou are a Microfyxd code generator. Return only code, no markdown fences." },
        { role: "user", content: `Generate a handler for ${state.targetFile}.` },
      ]);
      if (typeof res.content === "string" && res.content.trim()) newCode = res.content.trim();
    } catch { /* fall back to stub */ }
  }

  return {
    code: newCode,
    generatedCode: newCode,
    next: "sandboxTest",
    logEntries: [...(state.logEntries || []), { step: "writeCode", message: `Generated ${newCode.length} chars for ${state.targetFile}`, timestamp: new Date().toISOString(), level: "info" }],
  };
}
